package.json

Set `private: true` in package.json.
By doing this, npm will reject any attempts to publish the package (we only want this published in the vscode extension marketplace).

set private to true

---

package.json

resolves this compile error:
` ERROR  You should not depend on 'vscode' in your 'dependencies'. Did you mean to add it to 'devDependencies'?`

move vscode to devDependencies

---

.vscode/launch.json

the previous webpack pr breaks the vscode debug mode, this patch will fix it. manually tested.

fix(.vscode): use webpack to run debug mode

---

package.json

In the vscode marketplace (https://marketplace.visualstudio.com/items?itemName=influxdata.flux), clicking the "Repository" link goes to an invalid github url. This will fix that.

use correct package repository

---

package.json
src/components/connections/Connection.ts

close https://github.com/influxdata/vsflux/issues/83
removed the run query from connection node.
add confirmation before delete

chore(UI): reorder sub menu

---

src/components/Query.ts
src/components/connections/Connection.ts

- fix some minor issue if the query response is too large.
- cut the additional headers additional data
- set the current connection to default

fix(query): minor fix for large response

---

package.json
src/components/connections/Connection.ts
src/components/connections/ConnectionNode.ts

Changing "delete" to "remove" because I'm nitpicking and want the destructive command on the bottom of the list.
VSCode orders groups alphanumerically, so this changes the order.
Also adding a "no" option to the deletion modal instead of click "x" to cancel.

change delete connection to remove connection

---

CONTRIBUTING.md

We now use flux-lsp directly, so flux-lsp-cli is no longer necessary.

remove flux-lsp-cli from CONTRIBUTING

---

package.json
src/components/connections/EditConnectionView.ts
src/util.ts
templates/editConn.html
templates/editConn.js

close https://github.com/influxdata/vsflux/issues/129
dropped the default v2 url. When added a new connection, user will no longer need to delete the the input, to see the dropdown list

fix(connection): drop the default v2 url

---

package-lock.json
package.json

Helps with #167 
Still have yet to publish to the marketplace, but this bumps the version number and upgrades to the latest release of flux.

chore(lsp): Upgrade flux-lsp dependency to latest release

---

package.json

Adds missing InfluxDB Cloud regions to the InfluxDB v2 URLs list.

feat(hosts): Add new InfluxDB Cloud regions

---

syntaxes/flux.tmLanguage.json

This patch adds `testcase` to the highlighted control word list,
equivalent to `test` (and eventually replacing it).

feat: highlight testcase as a reserved word

---

package-lock.json
package.json
tag-release.sh

- Change version from v0.5.12 to v0.5.13
- Upgrade flux-lsp-node to v0.5.26
- Add newline to release notes in `tag-release.sh`

build: Release v0.5.13

---

package-lock.json
package.json

After accidentally upgrading to the latest version of the `vscode` library, it appears there was a breaking change to their `EventEmitter` api that was causing our build to fail. This reverts the version of `vscode` we're using back to 1.44, the last known compatible version.

build: lock vscode dependency to 1.44

---

.circleci/config.yml
package-lock.json
package.json
src/components/connections/Connection.ts

Upgrades the vscode extension library to the latest version, as per #208, and fixes the `refresh` method as described in the changelog for `vscode 1.45`: https://code.visualstudio.com/updates/v1_45
Also runs `npm audit fix` to address security vulnerabilities in old libraries.
Also adds a CI job to check for build errors.

fix: Upgrade vscode dependency to latest version

---

.circleci/config.yml
package-lock.json
package.json

- Change version from v0.5.27 to v0.5.28
Cutting a release so that we can publish the changes made in https://github.com/influxdata/vsflux/pull/215, which should resolve some outstanding installation issues with the VS Code marketplace.

build: Release v0.5.28

---

package-lock.json
package.json

- Change version from v0.5.28 to v0.5.29
- Import version 1.56.1 of the vscode engine, which addresses some security vulnerabilities, as notes in the [April 2021 release notes](https://code.visualstudio.com/updates/v1_56)
This update will allow users of VS Code 1.56.1 to install the extension. Users of 1.56.0 can still use the `v0.5.28` release.

build: Release v0.5.29

---

src/components/Query.ts
src/util.ts

Closes #218
The fix here is simple enough. Bring the `Flux` output stream into view (without stealing focus), whenever a user submits a query that fails.
I also added some minor changes to the logging output to make it more readable.

feat: Open Flux output channel when a query errors

---

src/components/Query.ts
src/components/connections/Connection.ts
src/util.ts

When a user is adding/editing a connection and they hit the `Test Connection` button, log an error and show the output if the connection fails.

chore: Log and show error when connection test fails

---

package.json
templates/editConn.js

Previously, if a user included a slash at the end of the url they entered in the `Hostname and Port` input field, the connection would fail. This patch fixes that by trimming any trailing slash characters in that input
I've also set the versions for the vscode engine and the vscode types library to be at least version `1.45.0`. This should prevent us from requiring users to install a specific version of VS Code going forward.

chore: Trim trailing slashes in user input

---

package-lock.json
package.json

Fixes #237
Additionally, a manual upgrade to `webpack` and `webpack-cli` was needed
to update it to a non-vulnerable version. See the commit message of that
revision for details.

fix: update module to support vscode 1.57

---

package-lock.json
package.json

- Bumps version to 0.5.33
- imports version `^1.57.1` of the vscode engine.
version 1.57.1 of the `vscode` engine contains some security patches that we should import: https://code.visualstudio.com/updates/v1_57

chore: Release v0.5.33

---

package-lock.json
package.json

An updated webpack seems to be generating javascript that ends up
being invalid(?) inside the VSCode execution engine. The way this
manifests is a lack of being able to find `utils` package in the node.js
stdlib.
We should look into why this webpack can't be updated, because it does
come with some `npm audit` noisiness, but for now, this updated webpack
makes a VSCode extension that doesn't even work.

fix: downgrade webpack

---

.vscodeignore

This patch updates `.vscodeignore` so we ship a thinner extension.

chore: update .vscodeignore

---

templates/editConn.html
templates/table.html

From the Department of How Did This Ever Work, I noticed that the Add
Connection ui was unstyled and didn't seem to work quite right. Upon
digging in, I noticed that the debug console was showing 404 for the css
and js files. After reading the `Webview` API docs thoroughly and not
really seeing breakages in access control, I realized that the `cssPath`
and `jsPath` mustache variables were surrounded with `{{}}`, which is
html entity escaped by default, whereas `{{{}}}` renders the string
as-is. Marking those variables as safe fixed the issue. I am unsure how
that _ever_ worked.

fix: address 404s in static resource references

---

templates/editConn.html
templates/editConn.js

The earlier influxdb version toggle didn't completely work. It didn't
set the hidden elements to be disabled, so they were trying to validate
while hidden (and thus the validation messages couldn't figure out where
to display the error message). When submitting the data, the detection
for which version was selected was using `0` in the logic rather than
`"0"`, which made the submission always think it was using influxdbv1.
This is the fix for #232.
Additionally, I discovered that `editConn.html` had invalid markup,
with erroneous `</div>` tags. Once that worked, the VSCode html plugin
then changed the whitespace. I agree with the changes the plugin made,
so I recommend viewing this patch ignoring whitespace.
Closes #232

fix: update influxdb version toggle

---

src/components/Query.ts

This patch changes a single line from using `encodeURI` which is for
encoding entire URIs, to `encodeURIComponent`, which is for uri encoding
a single string. The follow-on effect is that a connection's org name is
now properly escaped.
Fixes #226

fix: actually encode the connection org name

---

src/components/util/query.ts
templates/table.html
test/query.test.ts

This patch adds the table id to the table view when running queries.
Additionally, `npm run fmt` formatted an html file, so viewing the patch
without whitespace changes is recommended.
Closes #227

fix: add table id to "run query" results

---

.vscode/settings.json
package.json
src/components/connections/BucketNode.ts
src/components/connections/Connection.ts
src/components/connections/ConnectionNode.ts
src/components/connections/MeasurementNode.ts
src/components/util/query.ts
src/extension.ts

While investigating #228, I discovered a number of very awkward APIs,
and simplified things where I could, which made me discover other
issues, like `async` functions not being `await`ed. These changes
represent fixes for those small issues that weren't causing issues
before by sheer luck.

chore: minor bugfixes and refactors

---

.gitattributes
src/components/util/query.ts
test/fixtures/error.csv
test/query.test.ts

This patch adds support for displaying error tables in the table view. This
ollows malformed queries that error to be displayed similar to how they
would be displayed in the web ui.
Closes #224

fix: handle error tables

---

.gitattributes
package-lock.json
package.json
src/components/Client.ts

This patch updates vscode to use the new lspower-based server. Manual
testing indicates that it's at least equivalent to the old server,
though does have some issues with panics that may need to be addressed
either here or in the flux-lsp.
Closes #262

feat: update to lsp2

---

src/components/connections/ConnectionNode.ts

Somehow, the update to show table rows broke the treelist on the left
hand side and I didn't catch it. I'm certainly concerned about it, but I
don't currently have a way to prevent this regression outside of
`npm run clean` and manually verifying master before release.
I experienced this issue, but it was also reported as part of #266.

fix: fix connection listing

---

tag-release.sh

The previous tag/release script was hardcoded to only consider updates
to lsp. The script has been updated to provide a better changelog.

chore: update tag/release script

---

package.json

This patch completely removes some commands from the command palette.
The interface in `package.json` can be a bit confusing, and these
commands were still kinda leaking into the command palette.

fix: clean up command palette

---

package-lock.json
package.json
src/views/TreeView.ts

This patch adds a task listing to connections in the tree view when the
influxdb connection is a v2 connection.
Closes #275

feat: list tasks in influxdb tree view

---

package.json
src/extension.ts
src/views/TreeView.ts

This patch adds the ability to edit a task. In the tree view, find the
task to edit, right click and select "Edit task", and the task will be
opened in the editor. Edit the task (and run it, should you like), and
upon save, the contents of the file will be written back to the remote
influxdb instance.
Closes #277

feat: open task for editing

---

package.json
src/extension.ts
src/views/AddTaskView.ts
src/views/TreeView.ts
templates/addTask.html
templates/addTask.js
tsconfig.json

This patch adds a flow from creating a new task in vscode. Right-click
on "Tasks" and select "Add task" and follow the flow through until it's
been created and listed in the "Tasks" tree view.
Closes #276

feat: add flow for creating a new task from vscode

---

src/components/Client.ts

Usually, event handlers bind `this` to the event itself. It seems that
vscode seems to just not bind it at all, so `this` is `undefined`. The
issue with this is that the language client's event handlers then
reference `this` as though it's an instance of `Client`. This has never
actually worked, but I started seeing more often when I was testing the
task editing work.

fix: bind the event handlers

---

package-lock.json
package.json
src/views/TreeView.ts

This patch restores v1 connectivity, albeit with slightly less
functionality. Buckets in v1 can be listed, but dialing down to
measurements and tags cannot be.
In the future, v1 support will be on an as-requested, community-oriented
basis, and will not see active development.

feat: restore v1 connectivity

---

src/models.ts
templates/table.css
templates/table.html

This patch does a few things all related to how the table output is
shown. First, it uses an asterisk to indicate group keys. Second, it
fixes a bug where each row appeared to be its own table. Lastly, it
populates the `_result` field on the rows based on the default. It seems
that it doesn't show up in the row itself, so has to be divined from the
table head.
Closes #290

fix: display the table output more correctly

---

src/components/Store.ts
src/extension.ts
src/types.ts
src/views/TreeView.ts
templates/editConn.html
templates/editConn.js
templates/form.css

This patch adds support for disabling TLS verification. It adds a
property to the interface that is stored in vscode, and then adds the
plumbing to flip the bit in the UI.
Additionally, this patch introduces a `Store` singleton that allows us
to query various storage mechanisms in Code. Currently, it just
abstracts the current context global state. By doing this, we ensure
that the data model is enforced in one place (see the logic around
`isActive').
Closes #202

feat: allow disabling TLS verification

---

.eslintrc.json
package-lock.json
package.json
src/components/Client.ts
src/components/Debug.ts
src/extension.ts

This patch adds the start of a flux debugger. Currently, it duplicates
the work of the "Run query" functionality, and nothing more. This allows
users to hit F5 or use any of the Code-specific methods for running code
and have it executed.
Closes #293

feat: add a flux debugger

---

src/views/TreeView.ts

fix: filter out _start, _stop, and _field from tag list

---

src/components/APIClient.ts
src/components/Debug.ts
src/components/LSPClient.ts
src/components/QueryRunner.ts
src/components/Store.ts
src/extension.ts
src/types.ts
src/views/AddInstanceView.ts
src/views/TreeView.ts

This patch refactors a number of interfaces to make it easier to debug an issue where running a query resulted in "certificate has expired" errors. Upon doing that refactor and investigating, it appears an original LetsEncrypt root CA has expired today, and this was part of the fallout.

fix: embed letsencrypt root ca

---

package.json

Project-wide, the `Connection` logic became `Instance` because
"connection" could be all sorts of things. Unfortunately, the
`package.json` didn't get updated. This patch updates that file to fix
the missing event registrations.

fix: rename the package.json events from connection to instance

---

release.sh

The previous release script was a little complex. Luckily, the flux
release process has solved a lot of the same problems here by using a
temp dir and not caring anything about your working tree or your github
setup. This patch simplifies that process in the same way.

chore: adjust release script

---

src/views/TreeView.ts

This patch changes the way we detect the invocable scripts feature in
vsflux. Previously, it just checked the `instance.hostNport` against a
list of cloud instances. That broke when it came to cloud instances not
publicly accessible. This patch changes the functionality to check for
the script api, which has the added benefit of future proofing the logic
as well.

fix: check for script capability rather than hardcoding to cloud

---

src/views/TreeView.ts

This patch changes the tree view to dial in from
bucket->measurements->tags to bucket->measurements->fields.
Fixes #338

fix: get measurements field values, not tags

---

src/controllers/AddScriptController.ts
src/views/TreeView.ts

Part of the (current) flow to adding/editing tasks and scripts is to
create a temporary file on the filesystem. We use the name of task or
script as the filename, but when it has characters that are path
separators, that flow breaks. This patch makes a small change to fix
that issue.
Long term, we're currently re-thinking this flow entirely, and whether
we need to write a file at all, or if there's a better flow.
Fixes #349

fix: escape path separators in task/script names

---

templates/addScript.html

This patch makes the "Add Script" ui flow require descriptions.
Descriptions _should_ be optional, but the current data model requires
them. Rather than making something up, it's probably a better flow to
require the description in the UI.
Fixes #337

fix: enforce required script description

---

src/controllers/AddInstanceController.ts

Throwing the error does not work here so refactor it to use a Promise and await.
I were rather confused due to not receiving an feedback after not using the correct organization.

fix: Report an error when testing a v2 connection fails

---

package.json
src/extension.ts
src/test/suite/extension.test.ts
src/views/TreeView.ts

I don't see any tests for any similar feature so I just tested it manually, is features like this possible to test (easily)?
Closes #342

feat: Allow scripts and tasks to be renamed

---

package.json
src/extension.ts
src/test/suite/extension.test.ts
src/views/TreeView.ts

A new menu item is provided to give users access to the ID of scripts.
This should allow folks to invoke their scripts by other means (client
APIs) more easily since we don't currently have a nice way to view
these scripts in the web UI.
The command was named `copyResourceID` in anticipation for some later
day where we might want to use this with other resources (such as
Buckets, Tasks, or even _user defined packages_...). Technically there's
nothing "script specific" about the implementation.
Fixes #339
https://user-images.githubusercontent.com/301388/147778850-3944dd3b-bec1-4b33-b01d-c5ad282d0c31.mp4

feat: Add "Copy ID" menu item for Scripts

---

package-lock.json
package.json
src/components/LSPClient.ts

This patch removes the need to use the `through2` library. The node
landscape around `stream` has changed significantly since this work was
done. This api makes the structure a little easier to follow.

refactor: re-arrange `LSPClient`

---

package.json

If I were to guess, the `view == influxdb` constraint were meant to only show this command in the command pallete if the `influxdb` view were active, however it seems to just remove it from the command palette entirely. `Add Connection` seems to be the only command that does not need to run on a menu node so I removed its entry in `commandPallete` which effectively enables it in the command palette again (as the default is to show it there).
I tried to move the `when` clauses to be under `commands` instead which the documentation seems to indicate to be possible but that seems to have no effect, the commands are always displayed in the command pallete in case https://code.visualstudio.com/api/references/contribution-points#contributes.commands .
Removing the commands that shouldn't be in …

fix: Restore the Add connection command to the command pallete

---

src/controllers/AddInstanceController.ts

The static asset reference wasn't broken, but it wasn't using the
intended API, so it had the potential to break. As a result, I just
removed the methods that were only called once.

refactor: flatten controller for add/edit controls

---

src/components/APIClient.ts

It looks like electron has gotten their cert store figured out with
regard to the Let's Encrypt certs, so we can remove this workaround.

feat: remove the tls cert hack

---

package-lock.json
package.json
src/components/LSPClient.ts

This patch updates vsflux to use flux-lsp 0.8.x. It also simplifies the
stream into a single transformation, which makes it a bit easier to
divine what the transformation is actually doing.
Fixes #369

feat: update to flux-lsp 0.8.x

---

README.md
package.json
src/components/Migration.ts
src/components/Store.ts
src/controllers/AddInstanceController.ts
src/types.ts
src/views/TreeView.ts
templates/editConn.html

This patch adds support for backing the instance list using the cli
configuration rather than the vscode global state. This patch supports
create/read/update/delete operations using the `influx` command.
Upon updating the extension, a migration will attempt to see if there is
an `influx` command available. If it is, the user is prompted to choose
between vscode and the cli configuration. If the cli configuration is
chosen, all existing db-stored connections are migrated to the cli
configuration.
Fixes #295

feat: add cli configuration as a possible data source

---

package.json

We recently updated all the dependencies in vsflux, but the
`@types/node` version is tied to the extension's engine version when
publishing the extension, and so this blocked the released.
There doesn't seem to be a dry run of the publish to do a wellness check
on the config, or I would have added that to this.

fix: bump the engine version to a compatible node version type

---

package.json

_le sigh_
The error message this raises is confusing. It will say "You're using
types version X, but you need a version greater than Y", where Y is, I
guess, the current version, and has nothing to do with compatibility
with X. What it should say is "engine needs to be greater than or equal
to version X." My attempt to be conservative and not expect VSCode to be
super up-to-date (I was using 1.63.3) meant I still didn't fix it.
Updated vscode, bumped the engine version, and made a prerelease job
that allowed me to test that it'd work (but not actual publish
anything).
I will figure out how to test this better when it's not blocking a
release.

fix: bump engine version again

---

.circleci/config.yml
.circleci/prerelease.sh
release.sh

This patch fixes the prerelease flow, as it was less smart than I
originally expected. The version has to be bumped in `package.json`
before it can put out as a prerelease version, whereas I had assumed it
would do that automatically. Because that version cannot be committed
(we don't want our CI to commit things), a release script calculates
what the prerelease version should be, as `npm version prerelease`
can't maintain that state.
Additionally, it also fixes calculating changelogs for release notes,
as that seemed to not really work correctly.

chore: fix prerelease

---

src/components/Store.ts
src/controllers/AddInstanceController.ts
templates/editConn.js

It seems that the Add Connection flow got broken a bit when adding
support for the cli backend. This patch fixes the core issue described
in #375, but also fixes a couple of issues discovered in testing that
fix, mainly that spaces weren't allowed in name or org, and that the
messages from the "Test Connection" flow weren't working.
Fixes #375

fix: small fixes to Add Connection flow

---

src/components/QueryRunner.ts

When the backend work got put in place, `Store.getInstances` became an
async function. `QueryRunner` never got updated to the new change, and
no linter caught it, so when it tried to execute, it wouldn't find the
active instance before it merrily continued on its way without the
active instance. It would error, but never return, so it would actually
error twice. This has been fixed here.
I tried to add a lint rule that would force all `async` calls to be
`await`ed, but it was overly greedy, and would have made this patch much
bigger than seemed feasible for a bugfix.

fix: address getInstances being changed to async

---

package-lock.json
package.json

This patch updates outdated dependencies, as is becoming more of the
practice as we update `@influxdata/flux-lsp-node`.

chore: update outdated dependencies

---

package-lock.json

vsflux is affected by https://github.com/advisories/GHSA-xvch-5gv4-984h. A dependabot alert came in on 2022-03-25 but for some reason it is no longer listed. This PR used `npm audit fix` to adjust `package-lock.json` to update `minimist` from `1.2.5` to `1.2.6`. A quick look shows that `minimist` appears to be from only devDependencies which appear to be for building and linting and so not the high priority issue that the dependabot alert claims:
```
$ npm ls minimist
flux@1.0.3 /home/jamie/code/vsflux
├─┬ @vscode/test-electron@2.1.3
│ └─┬ unzipper@0.10.11
│   └─┬ fstream@1.0.12
│     └─┬ mkdirp@0.5.5
│       └── minimist@1.2.5  deduped
├─┬ eslint-plugin-import@2.25.4
│ └─┬ tsconfig-paths@3.12.0
│   ├─┬ json5@1.0.1
│   │ └── minimist@1.2.5  deduped
│   └── minimist@1.2.5 
└─┬ vsce@2.7.0 …
```

chore: update to use minimist 1.2.6

---

src/views/TreeView.ts

This patch adds support for seeing tag keys and values in the InfluxDB
pane's tree view. Rather than each measurement showing just the fields,
it now has two children, Fields and Tags. Fields then expands to show
all fields, and Tags expands to show tags. Those tag can then go another
step further and show tag values.
This work is all in preparation for testing out and prototyping some new
function injection functionality.

feat: add support for tags and tag value treeitems

---

src/components/APIClient.ts

The default query timeout is set to 10s. The default query timeout is
30s in the web ui. This patch updates the default timeout to match the
web ui.
Fixes #408

fix: update the timeout to match the web ui

---

src/controllers/AddInstanceController.ts
templates/editConn.html
templates/editConn.js

In the current plugin, when one tries to add a connection that either
has bad auth information or a bad network connection, the "save"
functionality has no feedback. Making a connection to the database is
important, as that's how we get the org id, which is needed for a few of
the requests we make.
This patch removes the "Test" functionality, as it is now unneeded, and
prevents adding databases with bad auth information.
Fixes #400

fix: only add connections that can be authenticated

---

package.json

Until the introduction of the cli datasource, there wasn't really a use
for the settings page of the extension. Even then, that feature was
mostly experimental, and we didn't want to expose it. At this point, I
think it makes sense to expose that on the settings page. This patch
exposes that setting on the settings page and removes an holdover from
the previous v1 support.

feat: allow changing settings via settings page

---

package-lock.json
package.json

Bug patch. Removed off-by-1 error in the schema composition applyEdit messages.

build(lsp): upgrade flux-lsp to 0.8.34
