package.json

Publisher is required to publish the extension in the marketplace; this adds it to package.json
Did some reordering of the package.json because I'm fussy

add publisher

---

package-lock.json
package.json

fix(src): fix vsce package

---

src/components/Client.ts

clean up error message

---

package-lock.json
package.json

manually tested with vsce package and install from vsix
also make sure delete the old extension in located in `~/.vscode/extensions/influxdata.flux-0.0.1/`, reload or uninstall the extension won't remove the cache

fix(dep): add lsp client dep to dep

---

package.json

fix(package.json): add ^ sign back to lsp client

---

src/executables/Tool.ts
src/extension.ts

We no longer need to reload the window anymore

fix(src/Executables): remove window reload after downloading the lsp

---

.gitignore
.vscodeignore
package-lock.json
package.json
webpack.config.js

close #https://github.com/influxdata/vsflux/issues/41
manually tested packed vsix in windows 10, ubuntu, macos
manually tested debug mode

feat(package.json): add webpack

---

package.json
src/executables/Tool.ts

this updates the display name to Flux, and changes some wording for the language server installation

change LS install verbage

---

README.md

Add badges for:
- vscode installs
- license
- community slack

add readme badges

---

CHANGELOG.md
CONTRIBUTING.md
README.md

closes #37
Added a changelog, then split readme out into a contributing doc.
Readme still needs to be fleshed out with a full description of features.

update README and add CHANGELOG and CONTRIBUTING

---

src/components/Query.ts
src/components/connections/Connection.ts
src/components/connections/ConnectionNode.ts
src/components/connections/Status.ts

Close https://github.com/influxdata/vsflux/issues/56
Added an id to the Current connection, set it to undefined when the id matches the deletion. Manually tested

fix(connections): remove current if match delete connection

---

package.json

version 0.1.0

---

CHANGELOG.md
src/components/connections/BucketNode.ts

fix the wrong hard coded bucket name 
```
Err: StatusCodeError: 404 - “{\“code\“:\“not found\“,\“message\“:\“failed to initialize execute state: could not find bucket \\\“buck1\\\“\”}“`
```

fix(connections): fix get the tag key

---

src/components/connections/BucketNode.ts

address the comment of pr [#71 ]

fix(connections): format the tagkeys query

---

package-lock.json
package.json
src/components/Query.ts
src/components/TableView.ts
src/components/View.ts
src/components/connections/Connection.ts
src/components/connections/ConnectionNode.ts
src/components/connections/EditConnectionView.ts
templates/editConn.js
templates/editConn.mst
templates/form.css

Add webview connection page to add, edit, test, save influxdb 2.0 connection. 
also addressed #68 and some feedbacks of vscode extension

fix(connections): add config page view

---

src/components/connections/EditConnectionView.ts

minor change to wording for connection webviews

update connection webview titles

---

templates/editConn.js
templates/editConn.mst
templates/form.css

close https://github.com/influxdata/vsflux/issues/80

fix(ui): add error to input field

---

package.json
src/components/Query.ts
src/components/connections/Connection.ts
src/components/connections/ConnectionNode.ts
src/components/connections/EditConnectionView.ts
src/components/connections/MeasurementNode.ts
templates/editConn.js
templates/editConn.mst
templates/form.css

close https://github.com/influxdata/vsflux/issues/74
add the influxdb v1 connection
added a measurement node, so the current tree structure will be buckets > measurements >tag keys

feat(connection): add influx v1 connection

---

src/components/connections/Connection.ts
src/components/connections/ConnectionNode.ts
src/components/connections/EditConnectionView.ts
templates/editConn.js
templates/editConn.mst

close https://github.com/influxdata/vsflux/issues/89
close https://github.com/influxdata/vsflux/issues/91
close https://github.com/influxdata/vsflux/issues/90

fix(connection): remove default connection

---

package.json
src/components/Query.ts
src/components/connections/EditConnectionView.ts
src/util.ts
templates/editConn.html

close https://github.com/influxdata/vsflux/issues/101

feat(connection): add datalist

---

package.json
src/components/Query.ts
src/components/connections/BucketNode.ts
src/components/connections/Connection.ts
src/components/connections/ConnectionNode.ts
src/components/connections/EditConnectionView.ts
src/components/connections/INode.ts
src/components/connections/MeasurementNode.ts
src/components/connections/StringNode.ts
src/util.ts
templates/editConn.html
templates/editConn.js

- switch to using html5 validation

Add logger and fix host on edit page

---

templates/editConn.html

remove the regex pattern for token

fix(template): remove regex pattern for token

---

package-lock.json
package.json

fix the blocking issue of non local built flux lsp

fix(package.json): fix non local flux lsp build

---

.circleci/config.yml
.gitignore
.vscodeignore
package-lock.json
package.json
src/ui-test/selenium.ts
tsconfig.json

Adding the framework of selenium testing of vscode plugin.

feat(ui-test): add selenium test

---

templates/editConn.html

show token string in connection view

---

package-lock.json
templates/editConn.html
templates/form.css

close https://github.com/influxdata/vsflux/issues/130
also updated a security warning from github

fix(template): fix the test button

---

package-lock.json
package.json
src/components/Client.ts

- Update server initialization

Upgrade LSP to 0.4.1

---

src/components/Query.ts
src/components/connections/BucketNode.ts
src/components/connections/ConnectionNode.ts
src/components/connections/MeasurementNode.ts

close https://github.com/influxdata/vsflux/issues/132
fix the triple Error in error message

fix(components): fix error message

---

src/components/connections/Connection.ts

close #139 
with the option `modal: true`, the modal won't disappear anymore

fix(components): fix delete confirmation dispears

---

bump-version.sh

fix(release): set upstream instead of pushing to master

---

package-lock.json
package.json

Change version from v0.5.6 to v0.5.7

build: Release v0.5.7

---

package-lock.json
package.json

Change version from v0.5.7 to v0.5.8

build: Release v0.5.8

---

package-lock.json
package.json

Change version from v0.5.8 to v0.5.9

build: Release v0.5.9

---

package-lock.json
package.json
tag-release.sh

- Change version from `v0.5.9` to `v0.5.10`
- Upgrade to [`flux-lsp v0.5.24`](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.24)

build: Release v0.5.10

---

package-lock.json
package.json

- Change version from v0.5.10 to v0.5.11
- Upgrade LSP to v0.5.25

build: Release v0.5.11

---

package-lock.json
package.json

Change version from v0.5.11 to v0.5.12

build: Release v0.5.12

---

package-lock.json
package.json

- Change version from v0.5.13 to v0.5.14
- Upgrade flux-lsp-node to [v0.5.27](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.27)

build: Release v0.5.14

---

bump-version.sh
package-lock.json
package.json

- Change version from v0.5.14 to v0.5.15
- Upgrade Flux LSP to [v0.5.33](https://github.com/influxdata/flux-lsp/releases/tag/v0.5.33)

build: Release v0.5.15

---

package-lock.json
package.json

- Change version from v0.5.15 to v0.5.16

build: Release v0.5.16

---

package-lock.json
package.json

- Change version from v0.5.16 to v0.5.17

build: Release v0.5.17

---

package-lock.json
package.json

- Change version from v0.5.17 to v0.5.18

build: Release v0.5.18

---

package-lock.json
package.json

- Change version from v0.5.18 to v0.5.19

build: Release v0.5.19

---

package-lock.json
package.json

- Change version from v0.5.19 to v0.5.20

build: Release v0.5.20

---

package-lock.json
package.json

- Change version from v0.5.20 to v0.5.21

build: Release v0.5.21

---

package-lock.json
package.json

- Change version from v0.5.21 to v0.5.22

build: Release v0.5.22

---

package-lock.json
package.json

- Change version from v0.5.22 to v0.5.23

build: Release v0.5.23

---

package-lock.json
package.json

- Change version from v0.5.23 to v0.5.24

build: Release v0.5.24

---

package-lock.json
package.json

- Change version from v0.5.24 to v0.5.25

build: Release v0.5.25

---

package-lock.json
package.json

- Change version from v0.5.25 to v0.5.26

build: Release v0.5.26

---

package-lock.json
package.json

- Change version from v0.5.29 to v0.5.30

build: Release v0.5.30

---

package-lock.json
package.json

- Change version from v0.5.30 to v0.5.31

build: Release v0.5.31

---

.circleci/config.yml
Makefile
index.d.ts
src/components/Client.ts
src/components/Query.ts
src/components/TableView.ts
src/components/View.ts
src/components/connections/BucketNode.ts
src/components/connections/Connection.ts
src/components/connections/ConnectionNode.ts
src/components/connections/ConnectionView.ts
src/components/connections/INode.ts
src/components/connections/MeasurementNode.ts
src/components/connections/Status.ts
src/components/connections/StringNode.ts
src/components/util/query.ts
src/extension.ts
src/util.ts
tsfmt.json

- Sets `convertTabsToSpaces` in `tsfmt.json` to `true`
- Adds a `checkfmt` target to the makefile
- Installs the typescript formatter and adds a `checkfmt` job to ci

chore: Enforce consistent formatting for typescript files

---

package-lock.json
package.json

- Change version from v0.5.31 to v0.5.32

build: Release v0.5.32

---

bump-version.sh
tag-release.sh

chore: Update scripts to be mac compatible

---

package-lock.json
package.json

build: Release v0.5.35

---

package-lock.json
package.json

build: Release v0.5.36

---

src/components/Query.ts
src/components/connections/Connection.ts
templates/editConn.html
templates/editConn.js

feat: Get username + password in v1 connection form

---

package-lock.json
package.json
src/components/Client.ts
src/components/Query.ts
src/components/connections/Status.ts
tsconfig.json

While tracking domn some other issues inside vscode, I did some
housecleaning that resulted in this patch. I figured it made sense to
just commit it.

chore: update some out of date dependencies and get stricter lints

---

package.json
src/extension.ts
src/views/TreeView.ts

This patch adds the ability to delete a task via right clicking on a task
in the tree view.
Closes #278

feat: add the ability to delete a task via the tree view

---

src/views/TreeView.ts

While recording a demo, I discovered an issue where the old file isn't
cleaned up. I had originally assumed that `os.tmpdir` would create a new
directory every time, but it just returns the existing one that has a
bunch of other files in it. This patch creates a random dir in that dir,
writes the file to that dir, and then cleans up the whole dir after
save.

fix: clean up the filesystem after editing a task

---

src/views/TreeView.ts

feat: add user-agent to api requests

---

package.json
src/extension.ts
src/views/AddBucketView.ts
src/views/TreeView.ts
templates/addBucket.html
templates/addBucket.js
tsconfig.json

This patch adds create/delete buckets functionality to the tree view.
Closes #279

feat: add create/delete buckets from tree view

---

README.md

chore: update README and vsflux marketplace description

---

src/views/TreeView.ts

Same thing as https://github.com/influxdata/vsflux/pull/356

fix: Report an error if a task could not be created

---

package.json
src/components/APIClient.ts
src/controllers/AddScriptController.ts
src/models.ts
src/views/TreeView.ts

Is this how we want to display it? There seems to be a table view that is opened when queries are run, should this use that as well?
What is the difference between scripts and queries? (Why couldn't this use the API for running "Queries"?)
Closes #330

feat: Print the output of an invoked script to output

---

src/views/TreeView.ts

Currently, we only get the first page of tasks and scripts. That means
that if you have more than the default 20 tasks or scripts, you only get
the first page in vscode. This patch fixes that, so now vscode will just
keep fetching tasks and scripts until there are no more to fetch.
Fixes #404

fix: support pagination in tasks and scripts

---

CONTRIBUTING.md

I recently went through the instructions for "Running a Local Language Server Build" and found part of it is out of date. This PR updates the instructions
Thanks @nathanielc for your help on setting up my local env and pointing this contributing file to me

chore: update the instructions for running a local lsp
